# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: push
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Hello world action
    - uses: secrethub/actions/env-export@v0.1.0
    env: # Or as an environment variable
      GOOGLE_AUTH_INFO: ${{ secrets.GOOGLE_AUTH_INFO }}
